### ISSUE TITLE
What is this `realtime` package you are using?

### ISSUE THREAD

**Issue by mitchbregs** [jerempjerem/opensea-stream-py#1]
https://github.com/jerempjerem/opensea-stream-py/blob/502f272a3659852f4451e0821d6bdd04755eb689/setup.py#L6

Getting an error:

```
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    Client = OpenseaStreamClient(OPENSEA_API_KEY, Network.TESTNET)
  File "/home/ec2-user/src/opensea_stream.py", line 9, in __init__
    self.socket = Socket(socketUrl)
  File "/home/ec2-user/src/venv/lib64/python3.7/site-packages/realtime/connection.py", line 51, in __init__
    self.channels = cast(defaultdict[str, List[Channel]], self.channels)
TypeError: 'type' object is not subscriptable
```

**Comment by mitchbregs** [comment]
Nevermind, I found it (https://github.com/supabase-community/realtime-py)... but still confused about the err

**Comment by mitchbregs** [comment]
Looks like updates to `0.0.5` caused issues. Reverting back to `0.0.4` worked!

**Comment by anselal** [comment]
> Looks like updates to `0.0.5` caused issues. Reverting back to `0.0.4` worked!

thnx for the feedback, had the same problem and reverting back to 0.0.4 from 1.0.0 did the trick ;)

**Comment by 0xStaifane** [comment]
good !
